#ifndef ANCMP_ANDROID_ERRNO_H
#define ANCMP_ANDROID_ERRNO_H

#ifdef _WIN32
#include <windows.h>
#else
#include <pthread.h>
#endif

#define ANDROID_EPERM 1  
#define ANDROID_ENOENT 2  
#define ANDROID_ESRCH 3  
#define ANDROID_EINTR 4  
#define ANDROID_EIO 5  
#define ANDROID_ENXIO 6  
#define ANDROID_E2BIG 7  
#define ANDROID_ENOEXEC 8  
#define ANDROID_EBADF 9  
#define ANDROID_ECHILD 10  
#define ANDROID_EAGAIN 11  
#define ANDROID_ENOMEM 12  
#define ANDROID_EACCES 13  
#define ANDROID_EFAULT 14  
#define ANDROID_ENOTBLK 15  
#define ANDROID_EBUSY 16  
#define ANDROID_EEXIST 17  
#define ANDROID_EXDEV 18  
#define ANDROID_ENODEV 19  
#define ANDROID_ENOTDIR 20  
#define ANDROID_EISDIR 21  
#define ANDROID_EINVAL 22  
#define ANDROID_ENFILE 23  
#define ANDROID_EMFILE 24  
#define ANDROID_ENOTTY 25  
#define ANDROID_ETXTBSY 26  
#define ANDROID_EFBIG 27  
#define ANDROID_ENOSPC 28  
#define ANDROID_ESPIPE 29  
#define ANDROID_EROFS 30  
#define ANDROID_EMLINK 31  
#define ANDROID_EPIPE 32  
#define ANDROID_EDOM 33  
#define ANDROID_ERANGE 34  
#define ANDROID_EDEADLK 35  
#define ANDROID_ENAMETOOLONG 36  
#define ANDROID_ENOLCK 37  
#define ANDROID_ENOSYS 38  
#define ANDROID_ENOTEMPTY 39  
#define ANDROID_ELOOP 40  
#define ANDROID_EWOULDBLOCK ANDROID_EAGAIN  
#define ANDROID_ENOMSG 42  
#define ANDROID_EIDRM 43  
#define ANDROID_ECHRNG 44  
#define ANDROID_EL2NSYNC 45  
#define ANDROID_EL3HLT 46  
#define ANDROID_EL3RST 47  
#define ANDROID_ELNRNG 48  
#define ANDROID_EUNATCH 49  
#define ANDROID_ENOCSI 50  
#define ANDROID_EL2HLT 51  
#define ANDROID_EBADE 52  
#define ANDROID_EBADR 53  
#define ANDROID_EXFULL 54  
#define ANDROID_ENOANO 55  
#define ANDROID_EBADRQC 56  
#define ANDROID_EBADSLT 57  
#define ANDROID_EDEADLOCK ANDROID_EDEADLK
#define ANDROID_EBFONT 59  
#define ANDROID_ENOSTR 60  
#define ANDROID_ENODATA 61  
#define ANDROID_ETIME 62  
#define ANDROID_ENOSR 63  
#define ANDROID_ENONET 64  
#define ANDROID_ENOPKG 65  
#define ANDROID_EREMOTE 66  
#define ANDROID_ENOLINK 67  
#define ANDROID_EADV 68  
#define ANDROID_ESRMNT 69  
#define ANDROID_ECOMM 70  
#define ANDROID_EPROTO 71  
#define ANDROID_EMULTIHOP 72  
#define ANDROID_EDOTDOT 73  
#define ANDROID_EBADMSG 74  
#define ANDROID_EOVERFLOW 75  
#define ANDROID_ENOTUNIQ 76  
#define ANDROID_EBADFD 77  
#define ANDROID_EREMCHG 78  
#define ANDROID_ELIBACC 79  
#define ANDROID_ELIBBAD 80  
#define ANDROID_ELIBSCN 81  
#define ANDROID_ELIBMAX 82  
#define ANDROID_ELIBEXEC 83  
#define ANDROID_EILSEQ 84  
#define ANDROID_ERESTART 85  
#define ANDROID_ESTRPIPE 86  
#define ANDROID_EUSERS 87  
#define ANDROID_ENOTSOCK 88  
#define ANDROID_EDESTADDRREQ 89  
#define ANDROID_EMSGSIZE 90  
#define ANDROID_EPROTOTYPE 91  
#define ANDROID_ENOPROTOOPT 92  
#define ANDROID_EPROTONOSUPPORT 93  
#define ANDROID_ESOCKTNOSUPPORT 94  
#define ANDROID_EOPNOTSUPP 95  
#define ANDROID_ENOTSUP ANDROID_EOPNOTSUPP
#define ANDROID_EPFNOSUPPORT 96  
#define ANDROID_EAFNOSUPPORT 97  
#define ANDROID_EADDRINUSE 98  
#define ANDROID_EADDRNOTAVAIL 99  
#define ANDROID_ENETDOWN 100  
#define ANDROID_ENETUNREACH 101  
#define ANDROID_ENETRESET 102  
#define ANDROID_ECONNABORTED 103  
#define ANDROID_ECONNRESET 104  
#define ANDROID_ENOBUFS 105  
#define ANDROID_EISCONN 106  
#define ANDROID_ENOTCONN 107  
#define ANDROID_ESHUTDOWN 108  
#define ANDROID_ETOOMANYREFS 109  
#define ANDROID_ETIMEDOUT 110  
#define ANDROID_ECONNREFUSED 111  
#define ANDROID_EHOSTDOWN 112  
#define ANDROID_EHOSTUNREACH 113  
#define ANDROID_EALREADY 114  
#define ANDROID_EINPROGRESS 115  
#define ANDROID_ESTALE 116  
#define ANDROID_EUCLEAN 117  
#define ANDROID_ENOTNAM 118  
#define ANDROID_ENAVAIL 119  
#define ANDROID_EISNAM 120  
#define ANDROID_EREMOTEIO 121  
#define ANDROID_EDQUOT 122  
#define ANDROID_ENOMEDIUM 123  
#define ANDROID_EMEDIUMTYPE 124  
#define ANDROID_ECANCELED 125  
#define ANDROID_ENOKEY 126  
#define ANDROID_EKEYEXPIRED 127  
#define ANDROID_EKEYREVOKED 128  
#define ANDROID_EKEYREJECTED 129  
#define ANDROID_EOWNERDEAD 130  
#define ANDROID_ENOTRECOVERABLE 131 

#ifdef _WIN32
extern DWORD android_errno_key;
#else
extern pthread_key_t android_errno_key;
#endif

int android_errno_init(void);

int *android_errno(void);

int android_strerror_r(int errnum, char *strerrbuf, size_t buflen);

char *android_strerror(int errnum);

#endif
