LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := ancmp
LOCAL_SRC_FILES := \
    ./ancmp/string/android_bcopy.c \
    ./ancmp/string/android_index.c \
    ./ancmp/string/android_memccpy.c \
    ./ancmp/string/android_memchr.c \
    ./ancmp/string/android_memcmp.c \
    ./ancmp/string/android_memcpy.c \
    ./ancmp/string/android_memmem.c \
    ./ancmp/string/android_memmove.c \
    ./ancmp/string/android_memrchr.c \
    ./ancmp/string/android_memset.c \
    ./ancmp/string/android_memswap.c \
    ./ancmp/string/android_strcasecmp.c \
    ./ancmp/string/android_strcasestr.c \
    ./ancmp/string/android_strcat.c \
    ./ancmp/string/android_strchr.c \
    ./ancmp/string/android_strcmp.c \
    ./ancmp/string/android_strcoll.c \
    ./ancmp/string/android_strcpy.c \
    ./ancmp/string/android_strcspn.c \
    ./ancmp/string/android_strdup.c \
    ./ancmp/string/android_strlcat.c \
    ./ancmp/string/android_strlcpy.c \
    ./ancmp/string/android_strlen.c \
    ./ancmp/string/android_strncat.c \
    ./ancmp/string/android_strncmp.c \
    ./ancmp/string/android_strncpy.c \
    ./ancmp/string/android_strndup.c \
    ./ancmp/string/android_strnlen.c \
    ./ancmp/string/android_strpbrk.c \
    ./ancmp/string/android_strrchr.c \
    ./ancmp/string/android_strsep.c \
    ./ancmp/string/android_strspn.c \
    ./ancmp/string/android_strstr.c \
    ./ancmp/string/android_strtok.c \
    ./ancmp/string/android_strtotimeval.c \
    ./ancmp/string/android_strxfrm.c \
    ./ancmp/wchar/android_wcpcpy.c \
    ./ancmp/wchar/android_wcpncpy.c \
    ./ancmp/wchar/android_wcscasecmp.c \
    ./ancmp/wchar/android_wcscat.c \
    ./ancmp/wchar/android_wcschr.c \
    ./ancmp/wchar/android_wcscmp.c \
    ./ancmp/wchar/android_wcscoll.c \
    ./ancmp/wchar/android_wcscpy.c \
    ./ancmp/wchar/android_wcscspn.c \
    ./ancmp/wchar/android_wcsdup.c \
    ./ancmp/wchar/android_wcslcat.c \
    ./ancmp/wchar/android_wcslcpy.c \
    ./ancmp/wchar/android_wcslen.c \
    ./ancmp/wchar/android_wcsncasecmp.c \
    ./ancmp/wchar/android_wcsncat.c \
    ./ancmp/wchar/android_wcsncmp.c \
    ./ancmp/wchar/android_wcsncpy.c \
    ./ancmp/wchar/android_wcsnlen.c \
    ./ancmp/wchar/android_wcspbrk.c \
    ./ancmp/wchar/android_wcsrchr.c \
    ./ancmp/wchar/android_wcsspn.c \
    ./ancmp/wchar/android_wcsstr.c \
    ./ancmp/wchar/android_wcstok.c \
    ./ancmp/wchar/android_wcswidth.c \
    ./ancmp/wchar/android_wcsxfrm.c \
    ./ancmp/wchar/android_wctype.c \
    ./ancmp/wchar/android_wmemchr.c \
    ./ancmp/wchar/android_wmemcmp.c \
    ./ancmp/wchar/android_wmemcpy.c \
    ./ancmp/wchar/android_wmemmove.c \
    ./ancmp/wchar/android_wmemset.c \
    ./ancmp/tzcode/android_strftime.c \
    ./ancmp/tzcode/android_tz.c \
    ./ancmp/inet/android_inet_ntop.c \
    ./ancmp/abi_fix.c \
    ./ancmp/android_aeabi.c \
    ./ancmp/android_arc4random.c \
    ./ancmp/android_atomic.c \
    ./ancmp/android_ctype.c \
    ./ancmp/android_cxa.c \
    ./ancmp/android_cxa_guard.c \
    ./ancmp/android_dirent.c \
    ./ancmp/android_dlfcn.c \
    ./ancmp/android_errno.c \
    ./ancmp/android_fcntl.c \
    ./ancmp/android_fnmatch.c \
    ./ancmp/android_futex.c \
    ./ancmp/android_io.c \
    ./ancmp/android_ioctl.c \
    ./ancmp/android_logd.c \
    ./ancmp/android_math.c \
    ./ancmp/android_mmap.c \
    ./ancmp/android_operator_new.c \
    ./ancmp/android_posix_types.c \
    ./ancmp/android_pthread.c \
    ./ancmp/android_pthread_attr.c \
    ./ancmp/android_pthread_cond.c \
    ./ancmp/android_pthread_key.c \
    ./ancmp/android_pthread_mutex.c \
    ./ancmp/android_pthread_threads.c \
    ./ancmp/android_socket.c \
    ./ancmp/android_sprint.c \
    ./ancmp/android_stat.c \
    ./ancmp/android_strto.c \
    ./ancmp/android_sysconf.c \
    ./ancmp/android_thread_id.c \
    ./ancmp/android_time.c \
    ./ancmp/debugger.c \
    ./ancmp/hooks.c \
    ./ancmp/linker.c \
    ./ancmp/linker_debug.c \
    ./ancmp/linker_environ.c \
    ./ancmp/linker_format.c \
    ./ancmp/posix_funcs.c \
    ./ancmp/rt.c

LOCAL_C_INCLUDES := $(LOCAL_PATH)/
LOCAL_CFLAGS += -DLINKER_DEBUG=0

include $(BUILD_STATIC_LIBRARY)
