#ifndef ANDROID_WCHAR_H
#define ANDROID_WCHAR_H

#include "android_wchar_internal.h"
#include "android_wcschr.h"
#include "android_wcsdup.h"
#include "android_wcsncat.h"
#include "android_wcsrchr.h"
#include "android_wmemchr.h"
#include "android_wcpcpy.h"
#include "android_wcscmp.h"
#include "android_wcslcat.h"
#include "android_wcsncmp.h"
#include "android_wcsspn.h"
#include "android_wmemcmp.h"
#include "android_wcpncpy.h"
#include "android_wcscoll.h"
#include "android_wcslcpy.h"
#include "android_wcsncpy.h"
#include "android_wcsstr.h"
#include "android_wmemcpy.h"
#include "android_wcscasecmp.h"
#include "android_wcscpy.h"
#include "android_wcslen.h"
#include "android_wcsnlen.h"
#include "android_wcstok.h"
#include "android_wmemmove.h"
#include "android_wcscat.h"
#include "android_wcscspn.h"
#include "android_wcsncasecmp.h"
#include "android_wcspbrk.h"
#include "android_wcsxfrm.h"
#include "android_wmemset.h"
#include "android_wctype.h"

#endif
